import {
  faUser,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faBan,
  faTimes,
  faArrowLeft,
  faSave,
  faPlus,
  faPencilAlt,
  faTable,
  faMountain,
  faCheck,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faLongArrowAltRight,
  faLongArrowAltDown,
  faInfoCircle,
  faMapMarkedAlt,
  faStore,
  faStar,
  faClock,
  faQuoteLeft,
  faQuoteRight,
  faThumbsUp,
  faThumbsDown,
  faShareAlt,
  faHeart,
  faUserCircle,
  faHistory,
  faAddressCard,
  faShoppingBag,
  faCog, faCaretDown, faCaretUp, faSearch, faShoppingCart, faGlobeAmericas, faCoffee, faCartPlus,
} from '@fortawesome/free-solid-svg-icons';

import {faFacebook, faTwitter, faInstagram, faEnvira} from '@fortawesome/free-brands-svg-icons';


export const altroVendorIcons = [
  // registra icone vendor
];

export const icons = [
  faGlobeAmericas,
  faCoffee,
  faTwitter,
  faInstagram,
  faFacebook,
  faUser,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faBan,
  faTimes,
  faArrowLeft,
  faSave,
  faPlus,
  faPencilAlt,
  faTable,
  faMountain,
  faCheck,
  faTimes,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faPlus,
  faLongArrowAltRight,
  faLongArrowAltDown,
  faInfoCircle,
  faMapMarkedAlt,
  faStore,
  faStar,
  faEnvira,
  faClock,
  faQuoteLeft,
  faQuoteRight,
  faThumbsUp,
  faThumbsDown,
  faShareAlt,
  faHeart,
  faUserCircle,
  faHistory,
  faAddressCard,
  faShoppingBag,
  faCog,
  faCaretDown,
  faCaretUp,
  faSearch,
  faShoppingCart,
  faCartPlus
];
